### PR TITLE
Fix mobile extractor missing paid result description

### PR DESCRIPTION
**Pull request by ericHao22**
Fix paid result description missing issue in mobile extractor, and also prepare docker environment for local development.

### CODE REVIEW

**Comment by metalwarrior665** [comment]
Thanks a ton! Will test the new selectors.

**Comment by ericHao22** [comment]
No problems. Kindly let me know if there is any feedback.

**Review by chenghung — APPROVED** [review]
r+

**Review by metalwarrior665 — APPROVED** [review]
Merging and will test in beta on Apify. Thanks a lot

**Comment by ericHao22** [comment]
Thanks for your cooperation. And might I ask how soon could we run the actor built with latest code on Apify?

**Comment by metalwarrior665** [comment]
@ericHao22 It is in latest, thanks

**Comment by ericHao22** [comment]
Got it, thanks!!

**Pull request merged**
